### ISSUE TITLE
fresh install npm start fails

### ISSUE THREAD

**Issue by pscott-au** [cornflourblue/angular2-registration-login-example#5] opened 2017-07-02 05:48 UTC
Node -v = v6.10.2
NPM -v = 5.0.3

## NPM Install Warning
````shell
$ npm install
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> fsevents@1.1.2 install /Users/peter/angular2-registration-login-example/node_modules/fsevents
> node install

[fsevents] Success: "/Users/peter/angular2-registration-login-example/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm notice created a lockfile as package-lock.json. You should commit this file.
added 458 packages in 21.754s
````

## NPM Start Error
````shell
> $ npm start
> angular2-registration-login-example@1.0.0 start /Users/peter/angular2-registration-login-example
> tsc && concurrently "npm run tsc:w" "npm run lite"

node_modules/rxjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
node_modules/rxjs/observable/dom/WebSocketSubject.d.ts(24,22): error TS2415: Class 'WebSocketSubject<T>' incorrectly extends base class 'AnonymousSubject<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => WebSocketSubject<R>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<T>'.
      Type 'WebSocketSubject<R>' is not assignable to type 'Observable<T>'.
        Types of property 'operator' are incompatible.
          Type 'Operator<any, R>' is not assignable to type 'Operator<any, T>'.
            Type 'R' is not assignable to type 'T'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular2-registration-login-example@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular2-registration-login-example@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
````

**Comment by cornflourblue** [comment] 2017-07-13 06:01
This is working now, it was caused by a bug in RxJS 5.4.1 and TypeScript 2.4.1, it was fixed in RxJS 5.4.2

More info at https://github.com/Microsoft/TypeScript/issues/16593#issuecomment-313389674

**Closed as completed by cornflourblue** 2017-07-13 06:01 UTC
